apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name | default "redis" }}
spec:
  selector:
    app: {{ .Values.redis.name | default "redis" }}
  ports:
    - port: 6379
      targetPort: {{ .Values.redis.containerPort | default 6379 }}
  type: ClusterIP
